server:
  port: 8760

eureka:
  instance:
    prefer-ip-address: true
  #hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
   # serviceUrl:
   #   defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


spring:
  boot:
    admin:
      client:
        url: http://springboot-admin:8099
  application:
    name: eureka-server
management:
  endpoints:
    web:
      exposure:
        include: /*

info:
  version: @project.version@